site_name: Evelyn's Technical Writer Profile
nav:
  - About: index.md
  - 'Experience':
    - 'Education': 'education.md'
    - 'Work': 'work.md'
  - Skills: skills.md
  - Selected Past Work: selected.md
  - Contact: contact-page.md


theme:
  name: material
  logo: images/wizeline.png

extra_css:
  - css/extra.css